### ISSUE TITLE
TypeScript type definition

### ISSUE THREAD

**Issue by xt0rted** [github/query-selector#1]
I put together a TypeScript type definition for this library now that I'm using it. I could publish it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) but it's preferable to keep the definition in the package. Will you accept a PR with this or would you prefer to keep it separate?

**Comment by josh** [comment]
> Will you accept a PR with this or would you prefer to keep it separate?

Yes!
